[package]
name = "blog_os"
version = "0.1.0"
authors = ["Jordan Conard <jordan.conard3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
panic = "abort"

[panic.release]
panic = "abort"
